export interface EmojiEntry {
  emoji: string;
  keywords: string[];
  category: string;
}

export const EMOJI_KO_DATA: EmojiEntry[] = [

  // ── 운동 / 건강 ──
  { emoji: "💪", keywords: ["운동", "근육", "헬스", "힘", "강함", "gym"], category: "운동" },
  { emoji: "🏃", keywords: ["달리기", "조깅", "러닝", "운동", "run"], category: "운동" },
  { emoji: "🏋️", keywords: ["헬스", "운동", "웨이트", "역도", "gym"], category: "운동" },
  { emoji: "🧘", keywords: ["요가", "명상", "스트레칭", "yoga"], category: "운동" },
  { emoji: "⚽", keywords: ["축구", "soccer", "공"], category: "운동" },
  { emoji: "🏀", keywords: ["농구", "basketball"], category: "운동" },
  { emoji: "🎾", keywords: ["테니스", "tennis"], category: "운동" },
  { emoji: "🏊", keywords: ["수영", "swim"], category: "운동" },
  { emoji: "🚴", keywords: ["자전거", "사이클링", "bike"], category: "운동" },
  { emoji: "🥊", keywords: ["복싱", "격투", "boxing"], category: "운동" },
  { emoji: "⛹️", keywords: ["농구", "스포츠", "선수"], category: "운동" },
  { emoji: "🤸", keywords: ["체조", "스트레칭", "유연성"], category: "운동" },
  { emoji: "🏄", keywords: ["서핑", "파도", "surf"], category: "운동" },
  { emoji: "🧗", keywords: ["클라이밍", "등반", "산"], category: "운동" },


  // ── 목표 / 성취 ──
  { emoji: "🎯", keywords: ["목표", "타겟", "도전", "목적", "goal"], category: "목표" },
  { emoji: "🏆", keywords: ["트로피", "우승", "성공", "달성", "trophy", "win"], category: "목표" },
  { emoji: "🥇", keywords: ["1등", "금메달", "우승", "최고", "first"], category: "목표" },
  { emoji: "⭐", keywords: ["별", "최고", "스타", "star"], category: "목표" },
  { emoji: "🌟", keywords: ["별빛", "특별", "빛남", "star"], category: "목표" },
  { emoji: "✅", keywords: ["완료", "체크", "완성", "done", "check"], category: "목표" },
  { emoji: "💡", keywords: ["아이디어", "생각", "발견", "idea"], category: "목표" },
  { emoji: "📌", keywords: ["고정", "중요", "메모", "pin"], category: "목표" },
  { emoji: "🔑", keywords: ["열쇠", "해결", "key", "answer"], category: "목표" },
  { emoji: "💎", keywords: ["다이아몬드", "가치", "귀중", "diamond"], category: "목표" },
  { emoji: "🎖️", keywords: ["메달", "훈장", "성과", "medal"], category: "목표" },
  { emoji: "📚", keywords: ["책", "독서", "학습", "스터디", "book", "study"], category: "목표" },
  { emoji: "📖", keywords: ["책", "읽기", "독서", "book"], category: "목표" },
  { emoji: "✏️", keywords: ["연필", "필기", "메모", "pencil"], category: "목표" },
  { emoji: "📝", keywords: ["노트", "필기", "메모", "작성", "note"], category: "목표" },
  { emoji: "🎓", keywords: ["졸업", "학위", "대학", "graduation"], category: "목표" },
  { emoji: "📈", keywords: ["성장", "분석", "상승", "통계"], category: "목표" },
  { emoji: "🚀", keywords: ["로켓", "발사", "시작", "출시", "도전", "rocket"], category: "목표" },
  { emoji: "💻", keywords: ["노트북", "작업", "업무", "laptop"], category: "목표" },
  { emoji: "🔧", keywords: ["도구", "수리", "작업", "tool"], category: "목표" },
  { emoji: "📊", keywords: ["통계", "데이터", "분석", "차트"], category: "목표" },


  // ── 음악 / 예술 ──
  { emoji: "🎤", keywords: ["마이크", "발표", "노래", "mic"], category: "예술" },
  { emoji: "🎵", keywords: ["음악", "노래", "뮤직", "music"], category: "예술" },
  { emoji: "🎶", keywords: ["음악", "멜로디", "노래", "music"], category: "예술" },
  { emoji: "🎸", keywords: ["기타", "음악", "guitar"], category: "예술" },
  { emoji: "🎹", keywords: ["피아노", "건반", "음악", "piano"], category: "예술" },
  { emoji: "🥁", keywords: ["드럼", "음악", "drum"], category: "예술" },
  { emoji: "🎨", keywords: ["예술", "그림", "디자인", "art", "paint"], category: "예술" },
  { emoji: "🖌️", keywords: ["붓", "그림", "페인팅", "brush"], category: "예술" },
  { emoji: "📸", keywords: ["사진", "카메라", "photo", "camera"], category: "예술" },
  { emoji: "🎬", keywords: ["영화", "촬영", "film", "movie"], category: "예술" },
  { emoji: "🎮", keywords: ["게임", "플레이", "game"], category: "예술" },

  // ── 과일 ──
  { emoji: "🍎", keywords: ["사과", "빨간사과", "과일", "apple"], category: "과일" },
  { emoji: "🍊", keywords: ["귤", "오렌지", "과일", "orange", "tangerine"], category: "과일" },
  { emoji: "🍋", keywords: ["레몬", "시트러스", "과일", "lemon"], category: "과일" },
  { emoji: "🍋‍🟩", keywords: ["라임", "시트러스", "과일", "lime"], category: "과일" },
  { emoji: "🍇", keywords: ["포도", "grape", "과일"], category: "과일" },
  { emoji: "🍓", keywords: ["딸기", "strawberry", "과일"], category: "과일" },
  { emoji: "🫐", keywords: ["블루베리", "blueberry", "과일"], category: "과일" },
  { emoji: "🍒", keywords: ["체리", "cherry", "과일"], category: "과일" },
  { emoji: "🍑", keywords: ["복숭아", "peach", "과일"], category: "과일" },
  { emoji: "🥭", keywords: ["망고", "mango", "과일"], category: "과일" },
  { emoji: "🍍", keywords: ["파인애플", "pineapple", "과일"], category: "과일" },
  { emoji: "🥥", keywords: ["코코넛", "coconut", "과일"], category: "과일" },
  { emoji: "🍌", keywords: ["바나나", "banana", "과일"], category: "과일" },
  { emoji: "🍉", keywords: ["수박", "watermelon", "과일"], category: "과일" },
  { emoji: "🍈", keywords: ["메론", "멜론", "melon", "과일"], category: "과일" },
  { emoji: "🍐", keywords: ["배", "pear", "과일"], category: "과일" },
  { emoji: "🍏", keywords: ["초록사과", "그린애플", "과일", "green apple"], category: "과일" },
  { emoji: "🫒", keywords: ["올리브", "olive", "과일"], category: "과일" },
  { emoji: "🥝", keywords: ["키위", "kiwi", "과일"], category: "과일" },
  { emoji: "🍅", keywords: ["토마토", "tomato", "과일", "채소"], category: "과일" },

  // ── 음식 / 음료 ──
  { emoji: "☕", keywords: ["커피", "카페", "coffee"], category: "음식" },
  { emoji: "🧋", keywords: ["버블티", "밀크티", "boba", "bubble tea"], category: "음식" },
  { emoji: "🍵", keywords: ["차", "녹차", "tea"], category: "음식" },
  { emoji: "🥤", keywords: ["음료", "콜라", "소다", "drink"], category: "음식" },
  { emoji: "🍹", keywords: ["주스", "칵테일", "과일음료", "juice"], category: "음식" },
  { emoji: "🍷", keywords: ["와인", "red wine"], category: "음식" },
  { emoji: "🍺", keywords: ["맥주", "술", "beer"], category: "음식" },
  { emoji: "🍕", keywords: ["피자", "pizza"], category: "음식" },
  { emoji: "🍔", keywords: ["햄버거", "burger"], category: "음식" },
  { emoji: "🍟", keywords: ["감자튀김", "프라이", "fries"], category: "음식" },
  { emoji: "🌮", keywords: ["타코", "멕시칸", "taco"], category: "음식" },
  { emoji: "🍜", keywords: ["라면", "국수", "ramen", "noodle"], category: "음식" },
  { emoji: "🍣", keywords: ["초밥", "스시", "sushi"], category: "음식" },
  { emoji: "🥟", keywords: ["만두", "dumpling"], category: "음식" },
  { emoji: "🍛", keywords: ["카레", "curry"], category: "음식" },
  { emoji: "🍤", keywords: ["새우튀김", "튀김", "shrimp", "fried"], category: "음식" },
  { emoji: "🥗", keywords: ["샐러드", "다이어트", "야채", "salad"], category: "음식" },
  { emoji: "🥐", keywords: ["크루아상", "빵", "croissant"], category: "음식" },
  { emoji: "🧇", keywords: ["와플", "waffle"], category: "음식" },
  { emoji: "🍩", keywords: ["도넛", "donut"], category: "음식" },
  { emoji: "🍪", keywords: ["쿠키", "cookie"], category: "음식" },
  { emoji: "🍫", keywords: ["초콜릿", "chocolate"], category: "음식" },
  { emoji: "🍭", keywords: ["사탕", "캔디", "candy", "lollipop"], category: "음식" },
  { emoji: "🍦", keywords: ["아이스크림", "소프트콘", "ice cream"], category: "음식" },
  { emoji: "🎂", keywords: ["생일케이크", "생일", "birthday cake"], category: "음식" },
  { emoji: "🍰", keywords: ["케이크", "디저트", "cake"], category: "음식" },
  { emoji: "🧁", keywords: ["컵케이크", "cupcake"], category: "음식" },
  { emoji: "🍿", keywords: ["팝콘", "영화", "popcorn"], category: "음식" },

  // ── 자연 / 날씨 ──
  { emoji: "🌱", keywords: ["새싹", "성장", "식물", "시작", "plant"], category: "자연" },
  { emoji: "🌸", keywords: ["벚꽃", "꽃", "봄", "cherry"], category: "자연" },
  { emoji: "🌈", keywords: ["무지개", "rainbow", "색깔"], category: "자연" },
  { emoji: "☀️", keywords: ["태양", "맑음", "sun", "날씨"], category: "자연" },
  { emoji: "🌙", keywords: ["달", "밤", "moon"], category: "자연" },
  { emoji: "⚡", keywords: ["번개", "빠름", "전기", "lightning"], category: "자연" },
  { emoji: "🔥", keywords: ["불꽃", "화염", "열정", "fire", "hot"], category: "자연" },
  { emoji: "❄️", keywords: ["눈", "겨울", "차가움", "snow"], category: "자연" },
  { emoji: "🌊", keywords: ["파도", "바다", "물", "wave"], category: "자연" },
  { emoji: "🏔️", keywords: ["산", "등산", "mountain"], category: "자연" },
  { emoji: "🔭", keywords: ["천문", "우주", "별", "망원경"], category: "자연" },
  { emoji: "🔬", keywords: ["과학", "실험", "연구", "microscope"], category: "자연" },

  // ── 여행 / 장소 ──
  { emoji: "✈️", keywords: ["비행기", "여행", "출장", "plane"], category: "여행" },
  { emoji: "🌏", keywords: ["지구", "세계", "글로벌", "earth"], category: "여행" },
  { emoji: "🗺️", keywords: ["지도", "여행", "map"], category: "여행" },
  { emoji: "🏖️", keywords: ["바다", "해변", "휴가", "beach"], category: "여행" },
  { emoji: "🏕️", keywords: ["캠핑", "야외", "camping"], category: "여행" },
  { emoji: "🗼", keywords: ["에펠탑", "파리", "여행"], category: "여행" },
  { emoji: "🚆", keywords: ["기차", "여행", "train"], category: "여행" },
  { emoji: "🚗", keywords: ["자동차", "드라이브", "car"], category: "여행" },

  // ── 동물 (정면) ──
  { emoji: "🐶", keywords: ["강아지", "개", "dog", "puppy", "동물"], category: "동물" },
  { emoji: "🐱", keywords: ["고양이", "냥이", "cat", "kitten", "동물"], category: "동물" },
  { emoji: "🐻", keywords: ["곰", "bear", "동물"], category: "동물" },
  { emoji: "🐼", keywords: ["판다", "panda", "동물"], category: "동물" },
  { emoji: "🐨", keywords: ["코알라", "koala", "동물"], category: "동물" },
  { emoji: "🐯", keywords: ["호랑이", "tiger", "동물"], category: "동물" },
  { emoji: "🦁", keywords: ["사자", "lion", "동물"], category: "동물" },
  { emoji: "🐮", keywords: ["소", "젖소", "cow", "동물"], category: "동물" },
  { emoji: "🐷", keywords: ["돼지", "pig", "동물"], category: "동물" },
  { emoji: "🐸", keywords: ["개구리", "frog", "동물"], category: "동물" },
  { emoji: "🐵", keywords: ["원숭이", "monkey", "동물"], category: "동물" },
  { emoji: "🐔", keywords: ["닭", "chicken", "동물"], category: "동물" },
  { emoji: "🐧", keywords: ["펭귄", "penguin", "동물"], category: "동물" },
  { emoji: "🦉", keywords: ["부엉이", "올빼미", "owl", "동물"], category: "동물" },
  { emoji: "🦊", keywords: ["여우", "fox", "동물"], category: "동물" },
  { emoji: "🦋", keywords: ["나비", "butterfly", "동물"], category: "동물" },
  { emoji: "🐢", keywords: ["거북이", "turtle", "동물"], category: "동물" },
  { emoji: "🐙", keywords: ["문어", "octopus", "동물"], category: "동물" },
  { emoji: "🐰", keywords: ["토끼", "rabbit", "동물"], category: "동물" },
  { emoji: "🐹", keywords: ["햄스터", "hamster", "동물"], category: "동물" },
  { emoji: "🐭", keywords: ["생쥐", "쥐", "mouse", "동물"], category: "동물" },
  { emoji: "🦝", keywords: ["너구리", "라쿤", "raccoon", "동물"], category: "동물" },
  { emoji: "🐻‍❄️", keywords: ["북극곰", "흰곰", "polar bear", "동물"], category: "동물" },
  { emoji: "🦭", keywords: ["물개", "바다표범", "seal", "동물"], category: "동물" },
  { emoji: "🐣", keywords: ["부화", "병아리", "hatching", "동물"], category: "동물" },
  { emoji: "🐥", keywords: ["병아리", "아기새", "chick", "동물"], category: "동물" },
  { emoji: "🦜", keywords: ["앵무새", "parrot", "동물"], category: "동물" },
  { emoji: "🦚", keywords: ["공작", "peacock", "동물"], category: "동물" },
  { emoji: "🦀", keywords: ["게", "crab", "동물"], category: "동물" },
  { emoji: "🐠", keywords: ["물고기", "열대어", "fish", "동물"], category: "동물" },
  { emoji: "🐡", keywords: ["복어", "puffer fish", "동물"], category: "동물" },
  { emoji: "🐛", keywords: ["애벌레", "벌레", "caterpillar", "동물"], category: "동물" },

  // ── 감정 / 표현 ──
  { emoji: "😊", keywords: ["웃음", "행복", "기쁨", "미소", "smile"], category: "감정" },
  { emoji: "😄", keywords: ["활짝웃음", "기쁨", "신남", "grin"], category: "감정" },
  { emoji: "🥰", keywords: ["사랑", "좋아함", "귀여움", "love"], category: "감정" },
  { emoji: "😍", keywords: ["반함", "설렘", "사랑", "heart eyes"], category: "감정" },
  { emoji: "🤩", keywords: ["신남", "흥분", "스타", "star struck"], category: "감정" },
  { emoji: "😂", keywords: ["웃김", "재미", "laugh"], category: "감정" },
  { emoji: "🤣", keywords: ["빵터짐", "웃겨", "rolling laugh"], category: "감정" },
  { emoji: "😆", keywords: ["크게웃음", "재밌다", "laugh"], category: "감정" },
  { emoji: "😎", keywords: ["쿨함", "멋짐", "cool", "sunglasses"], category: "감정" },
  { emoji: "🥳", keywords: ["파티", "축하", "생일", "party"], category: "감정" },
  { emoji: "🤔", keywords: ["생각", "고민", "think"], category: "감정" },
  { emoji: "🧐", keywords: ["분석", "탐구", "monocle", "생각"], category: "감정" },
  { emoji: "😤", keywords: ["열정", "파이팅", "fighting"], category: "감정" },
  { emoji: "😅", keywords: ["식은땀", "당황", "sweat smile"], category: "감정" },
  { emoji: "😬", keywords: ["민망", "어색", "grimace"], category: "감정" },
  { emoji: "🥲", keywords: ["눈물", "감동", "슬픔", "holding back tears"], category: "감정" },
  { emoji: "😢", keywords: ["울음", "슬픔", "cry", "sad"], category: "감정" },
  { emoji: "😭", keywords: ["펑펑울음", "슬픔", "sob"], category: "감정" },
  { emoji: "😡", keywords: ["화남", "분노", "angry"], category: "감정" },
  { emoji: "🤯", keywords: ["충격", "놀람", "mind blown"], category: "감정" },
  { emoji: "😴", keywords: ["졸림", "잠", "피곤", "sleep"], category: "감정" },
  { emoji: "🤒", keywords: ["아픔", "병", "sick"], category: "감정" },
  { emoji: "🙌", keywords: ["박수", "칭찬", "응원", "cheer"], category: "감정" },
  { emoji: "👏", keywords: ["박수", "칭찬", "응원", "clap"], category: "감정" },
  { emoji: "🎉", keywords: ["파티", "축하", "이벤트", "party", "celebrate"], category: "감정" },
  { emoji: "❤️", keywords: ["하트", "사랑", "heart", "love"], category: "감정" },
  { emoji: "🧡", keywords: ["주황하트", "따뜻함", "orange heart"], category: "감정" },
  { emoji: "💛", keywords: ["노란하트", "행복", "yellow heart"], category: "감정" },
  { emoji: "💚", keywords: ["초록하트", "건강", "green heart"], category: "감정" },
  { emoji: "💙", keywords: ["파란하트", "신뢰", "blue heart"], category: "감정" },
  { emoji: "💜", keywords: ["보라하트", "감사", "purple heart"], category: "감정" },
  { emoji: "🖤", keywords: ["검은하트", "블랙", "black heart"], category: "감정" },
  { emoji: "🤍", keywords: ["흰하트", "순수", "white heart"], category: "감정" },
  { emoji: "💪", keywords: ["화이팅", "파이팅", "응원", "fighting"], category: "감정" },
  { emoji: "👍", keywords: ["좋아요", "최고", "thumbs up"], category: "감정" },
  { emoji: "✌️", keywords: ["브이", "승리", "peace", "victory"], category: "감정" },
  { emoji: "🤞", keywords: ["행운", "바람", "crossed fingers"], category: "감정" },
  { emoji: "🙏", keywords: ["감사", "부탁", "pray", "thank"], category: "감정" },
  { emoji: "🤝", keywords: ["악수", "협력", "팀워크", "handshake"], category: "감정" },
];

export const EMOJI_CATEGORIES = ["전체", "동물", "과일", "운동", "목표", "예술", "음식", "자연", "여행", "감정"];

export function searchEmoji(query: string): EmojiEntry[] {
  if (!query.trim()) return EMOJI_KO_DATA;
  const q = query.toLowerCase().trim();
  return EMOJI_KO_DATA.filter((entry) =>
    entry.keywords.some((kw) => kw.includes(q)) || entry.emoji.includes(q)
  );
}
